services:
  # db:
  #   image: postgres:16
  #   container_name: postgres16
  #   environment:
  #     POSTGRES_USER: usuarioapi1
  #     POSTGRES_PASSWORD: senhaapi1
  #     POSTGRES_DB: apidb
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/dat

  # mongodb:
  #   image: mongo:latest
  #   container_name: mongodb
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: admin
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db


volumes:
  # postgres_data:
  mongodb_data:
